### ISSUE TITLE
lots of ResourceWarnings

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/Python-Translators#24]
i get a lot of these things when i run the tests:

> **ResourceWarning: unclosed <ssl.SSLSocket** fd=11, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.43.241', 51809), raddr=('172.217.17.138', 443)>
>  **ResourceWarning: unclosed <ssl.SSLSocket** fd=11, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.43.241', 51810), raddr=('172.217.17.138', 443)>
> /Users/mircea/my/projects/zeeguu/server/env-z3/lib/python3.6/site-packages/oauth2client-4.1.0-py3.6.egg/oauth2client/_helpers.py:133: **ResourceWarning: unclosed <ssl.SSLSocket fd**=11, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.43.241', 51811), raddr=('172.217.17.138', 443)>
> /Users/mircea/my/projects/zeeguu/server/env-z3/lib/python3.6/site-packages/oauth2client-4.1.0-py3.6.egg/oauth2client/_helpers.py:133: **ResourceWarning: unclosed <ssl.SSLSocket fd=11,** family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.43.241', 51812), raddr=('172.217.17.138', 443)>
> /Users/mircea/my/projects/zeeguu/server/env-z3/lib/python3.6/site-packages/google_api_python_client-1.6.2-py3.6.egg/googleapiclient/discovery.py:161: **ResourceWarning: unclosed <ssl.SSLSocket fd=**8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.43.241', 51795), raddr=('172.217.17.106', 443)>
> /Users/mircea/my/projects/zeeguu/server/env-z3/lib/python3.6/site-packages/google_api_python_client-1.6.2-py3.6.egg/googleapiclient/discovery.py:161: ResourceWarning: unclosed <ssl.SSLSocket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.43.241', 51801), raddr=('172.217.17.106', 443)>
> /Users/mircea/my/projects/zeeguu/server/env-z3/lib/python3.6/site-packages/google_api_python_client-1.6.2-py3.6.egg/googleapiclient/discovery.py:161: ResourceWarning: unclosed <ssl.SSLSocket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.43.241', 51807), raddr=('172.217.17.106', 443

**Comment by mircealungu** [comment]
is there anything that we can do, or it's in the libraries? if so, do the warnings go away with the latest lib versions? if not, we should instruct the test infra to ignore them: https://stackoverflow.com/questions/26563711/disabling-python-3-2-resourcewarning

**Comment by thejager** [comment]
This has been a thing since upgrading to Python 3. I think this is happening somewhere in the Google library. It didn't really bother me, but I think I could just make it so that it suppresses the warnings. I don't think there is much else we can do.
