### ISSUE TITLE
do we still get these problems?

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/Python-Translators#29]
i thought we got rid of them :(
<img width="807" alt="screenshot 2017-06-30 16 19 53" src="https://user-images.githubusercontent.com/464519/27739773-080934fa-5db0-11e7-8b85-2078a896c046.png">

**Comment by thejager** [comment]
Whoops, I reintroduced this bug after moving to the query and response design.

Will be pushing a fix in a bit!
